
package org.ejbca.core.protocol.ws;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.3
 * 2018-08-06T10:49:50.904+02:00
 * Generated source version: 3.1.3
 */

@WebFault(name = "ApprovalRequestExecutionException", targetNamespace = "http://ws.protocol.core.ejbca.org/")
public class ApprovalRequestExecutionException_Exception extends Exception {
    
    private org.ejbca.core.protocol.ws.ApprovalRequestExecutionException approvalRequestExecutionException;

    public ApprovalRequestExecutionException_Exception() {
        super();
    }
    
    public ApprovalRequestExecutionException_Exception(String message) {
        super(message);
    }
    
    public ApprovalRequestExecutionException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public ApprovalRequestExecutionException_Exception(String message, org.ejbca.core.protocol.ws.ApprovalRequestExecutionException approvalRequestExecutionException) {
        super(message);
        this.approvalRequestExecutionException = approvalRequestExecutionException;
    }

    public ApprovalRequestExecutionException_Exception(String message, org.ejbca.core.protocol.ws.ApprovalRequestExecutionException approvalRequestExecutionException, Throwable cause) {
        super(message, cause);
        this.approvalRequestExecutionException = approvalRequestExecutionException;
    }

    public org.ejbca.core.protocol.ws.ApprovalRequestExecutionException getFaultInfo() {
        return this.approvalRequestExecutionException;
    }
}
