
package org.ejbca.core.protocol.ws;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.3
 * 2018-08-06T10:49:50.895+02:00
 * Generated source version: 3.1.3
 */

@WebFault(name = "ApprovalRequestExpiredException", targetNamespace = "http://ws.protocol.core.ejbca.org/")
public class ApprovalRequestExpiredException_Exception extends Exception {
    
    private org.ejbca.core.protocol.ws.ApprovalRequestExpiredException approvalRequestExpiredException;

    public ApprovalRequestExpiredException_Exception() {
        super();
    }
    
    public ApprovalRequestExpiredException_Exception(String message) {
        super(message);
    }
    
    public ApprovalRequestExpiredException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public ApprovalRequestExpiredException_Exception(String message, org.ejbca.core.protocol.ws.ApprovalRequestExpiredException approvalRequestExpiredException) {
        super(message);
        this.approvalRequestExpiredException = approvalRequestExpiredException;
    }

    public ApprovalRequestExpiredException_Exception(String message, org.ejbca.core.protocol.ws.ApprovalRequestExpiredException approvalRequestExpiredException, Throwable cause) {
        super(message, cause);
        this.approvalRequestExpiredException = approvalRequestExpiredException;
    }

    public org.ejbca.core.protocol.ws.ApprovalRequestExpiredException getFaultInfo() {
        return this.approvalRequestExpiredException;
    }
}
