
package org.ejbca.core.protocol.ws;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.3
 * 2018-09-27T08:23:56.032+02:00
 * Generated source version: 3.1.3
 */

@WebFault(name = "CAOfflineException", targetNamespace = "http://ws.protocol.core.ejbca.org/")
public class CAOfflineException_Exception extends Exception {
    
    private org.ejbca.core.protocol.ws.CAOfflineException caOfflineException;

    public CAOfflineException_Exception() {
        super();
    }
    
    public CAOfflineException_Exception(String message) {
        super(message);
    }
    
    public CAOfflineException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public CAOfflineException_Exception(String message, org.ejbca.core.protocol.ws.CAOfflineException caOfflineException) {
        super(message);
        this.caOfflineException = caOfflineException;
    }

    public CAOfflineException_Exception(String message, org.ejbca.core.protocol.ws.CAOfflineException caOfflineException, Throwable cause) {
        super(message, cause);
        this.caOfflineException = caOfflineException;
    }

    public org.ejbca.core.protocol.ws.CAOfflineException getFaultInfo() {
        return this.caOfflineException;
    }
}
