
package org.ejbca.core.protocol.ws;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.3
 * 2018-08-06T10:49:50.940+02:00
 * Generated source version: 3.1.3
 */

@WebFault(name = "CertificateExpiredException", targetNamespace = "http://ws.protocol.core.ejbca.org/")
public class CertificateExpiredException_Exception extends Exception {
    
    private org.ejbca.core.protocol.ws.CertificateExpiredException certificateExpiredException;

    public CertificateExpiredException_Exception() {
        super();
    }
    
    public CertificateExpiredException_Exception(String message) {
        super(message);
    }
    
    public CertificateExpiredException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public CertificateExpiredException_Exception(String message, org.ejbca.core.protocol.ws.CertificateExpiredException certificateExpiredException) {
        super(message);
        this.certificateExpiredException = certificateExpiredException;
    }

    public CertificateExpiredException_Exception(String message, org.ejbca.core.protocol.ws.CertificateExpiredException certificateExpiredException, Throwable cause) {
        super(message, cause);
        this.certificateExpiredException = certificateExpiredException;
    }

    public org.ejbca.core.protocol.ws.CertificateExpiredException getFaultInfo() {
        return this.certificateExpiredException;
    }
}
