
package org.ejbca.core.protocol.ws;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.3
 * 2018-08-06T10:49:50.906+02:00
 * Generated source version: 3.1.3
 */

@WebFault(name = "EjbcaException", targetNamespace = "http://ws.protocol.core.ejbca.org/")
public class EjbcaException_Exception extends Exception {
    
    private org.ejbca.core.protocol.ws.EjbcaException ejbcaException;

    public EjbcaException_Exception() {
        super();
    }
    
    public EjbcaException_Exception(String message) {
        super(message);
    }
    
    public EjbcaException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public EjbcaException_Exception(String message, org.ejbca.core.protocol.ws.EjbcaException ejbcaException) {
        super(message);
        this.ejbcaException = ejbcaException;
    }

    public EjbcaException_Exception(String message, org.ejbca.core.protocol.ws.EjbcaException ejbcaException, Throwable cause) {
        super(message, cause);
        this.ejbcaException = ejbcaException;
    }

    public org.ejbca.core.protocol.ws.EjbcaException getFaultInfo() {
        return this.ejbcaException;
    }
}
