package org.ejbca.core.protocol.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.3
 * 2018-08-06T10:49:50.946+02:00
 * Generated source version: 3.1.3
 * 
 */
@WebService(targetNamespace = "http://ws.protocol.core.ejbca.org/", name = "EjbcaWS")
@XmlSeeAlso({ObjectFactory.class})
public interface EjbcaWS {

    @WebMethod
    @RequestWrapper(localName = "getHardTokenData", targetNamespace = "http://ws.protocol.core.ejbca.org/", className = "org.ejbca.core.protocol.ws.GetHardTokenData")
    @ResponseWrapper(localName = "getHardTokenDataResponse", targetNamespace = "http://ws.protocol.core.ejbca.org/", className = "org.ejbca.core.protocol.ws.GetHardTokenDataResponse")
    @WebResult(name = "return", targetNamespace = "")
    public org.ejbca.core.protocol.ws.HardTokenDataWS getHardTokenData(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        boolean arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        boolean arg2
    ) throws NotFoundException_Exception, HardTokenDoesntExistsException_Exception, ApprovalRequestExpiredException_Exception, CADoesntExistsException_Exception, AuthorizationDeniedException_Exception, ApprovalRequestExecutionException_Exception, EjbcaException_Exception, WaitingForApprovalException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getProfile", targetNamespace = "http://ws.protocol.core.ejbca.org/", className = "org.ejbca.core.protocol.ws.GetProfile")
    @ResponseWrapper(localName = "getProfileResponse", targetNamespace = "http://ws.protocol.core.ejbca.org/", className = "org.ejbca.core.protocol.ws.GetProfileResponse")
    @WebResult(name = "return", targetNamespace = "")
    public byte[] getProfile(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    ) throws AuthorizationDeniedException_Exception, UnknownProfileTypeException_Exception, EjbcaException_Exception;

    @WebMethod
    @RequestWrapper(localName = "createCryptoToken", targetNamespace = "http://ws.protocol.core.ejbca.org/", className = "org.ejbca.core.protocol.ws.CreateCryptoToken")
    @ResponseWrapper(localName = "createCryptoTokenResponse", targetNamespace = "http://ws.protocol.core.ejbca.org/", className = "org.ejbca.core.protocol.ws.CreateCryptoTokenResponse")
    public void createCryptoToken(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        boolean arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        java.util.List<org.ejbca.core.protocol.ws.KeyValuePair> arg4
    ) throws AuthorizationDeniedException_Exception, EjbcaException_Exception;

    @WebMethod
    @RequestWrapper(localName = "crmfRequest", targetNamespace = "http://ws.protocol.core.ejbca.org/", className = "org.ejbca.core.protocol.ws.CrmfRequest")
    @ResponseWrapper(localName = "crmfRequestResponse", targetNamespace = "http://ws.protocol.core.ejbca.org/", className = "org.ejbca.core.protocol.ws.CrmfRequestResponse")
    @WebResult(name = "return", targetNamespace = "")
    public org.ejbca.core.protocol.ws.CertificateResponse crmfRequest(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        java.lang.String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        java.lang.String arg4
    ) throws AuthorizationDeniedException_Exception, NotFoundException_Exception, EjbcaException_Exception, CesecoreException_Exception, CADoesntExistsException_Exception;

    @WebMethod
    @RequestWrapper(localName = "findUser", targetNamespace = "http://ws.protocol.core.ejbca.org/", className = "org.ejbca.core.protocol.ws.FindUser")
    @ResponseWrapper(localName = "findUserResponse", targetNamespace = "http://ws.protocol.core.ejbca.org/", className = "org.ejbca.core.protocol.ws.FindUserResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<org.ejbca.core.protocol.ws.UserDataVOWS> findUser(
        @WebParam(name = "arg0", targetNamespace = "")
        org.ejbca.core.protocol.ws.UserMatch arg0
    ) throws AuthorizationDeniedException_Exception, EndEntityProfileNotFoundException_Exception, IllegalQueryException_Exception, EjbcaException_Exception;

    @WebMethod
    @RequestWrapper(localName = "genTokenCertificates", targetNamespace = "http://ws.protocol.core.ejbca.org/", className = "org.ejbca.core.protocol.ws.GenTokenCertificates")
    @ResponseWrapper(localName = "genTokenCertificatesResponse", targetNamespace = "http://ws.protocol.core.ejbca.org/", className = "org.ejbca.core.protocol.ws.GenTokenCertificatesResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<org.ejbca.core.protocol.ws.TokenCertificateResponseWS> genTokenCertificates(
        @WebParam(name = "arg0", targetNamespace = "")
        org.ejbca.core.protocol.ws.UserDataVOWS arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.util.List<org.ejbca.core.protocol.ws.TokenCertificateRequestWS> arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        org.ejbca.core.protocol.ws.HardTokenDataWS arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        boolean arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        boolean arg4
    ) throws ApprovalRequestExpiredException_Exception, CADoesntExistsException_Exception, AuthorizationDeniedException_Exception, HardTokenExistsException_Exception, UserDoesntFullfillEndEntityProfile_Exception, ApprovalException_Exception, EjbcaException_Exception, ApprovalRequestExecutionException_Exception, WaitingForApprovalException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getCertificatesByExpirationTimeAndType", targetNamespace = "http://ws.protocol.core.ejbca.org/", className = "org.ejbca.core.protocol.ws.GetCertificatesByExpirationTimeAndType")
    @ResponseWrapper(localName = "getCertificatesByExpirationTimeAndTypeResponse", targetNamespace = "http://ws.protocol.core.ejbca.org/", className = "org.ejbca.core.protocol.ws.GetCertificatesByExpirationTimeAndTypeResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<org.ejbca.core.protocol.ws.Certificate> getCertificatesByExpirationTimeAndType(
        @WebParam(name = "arg0", targetNamespace = "")
        long arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        int arg2
    ) throws EjbcaException_Exception;

    @WebMethod
    @RequestWrapper(localName = "revokeCertBackdated", targetNamespace = "http://ws.protocol.core.ejbca.org/", className = "org.ejbca.core.protocol.ws.RevokeCertBackdated")
    @ResponseWrapper(localName = "revokeCertBackdatedResponse", targetNamespace = "http://ws.protocol.core.ejbca.org/", className = "org.ejbca.core.protocol.ws.RevokeCertBackdatedResponse")
    public void revokeCertBackdated(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        int arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        java.lang.String arg3
    ) throws NotFoundException_Exception, AlreadyRevokedException_Exception, RevokeBackDateNotAllowedForProfileException_Exception, CADoesntExistsException_Exception, AuthorizationDeniedException_Exception, ApprovalException_Exception, DateNotValidException_Exception, EjbcaException_Exception, WaitingForApprovalException_Exception;

    @WebMethod
    @RequestWrapper(localName = "checkRevokationStatus", targetNamespace = "http://ws.protocol.core.ejbca.org/", className = "org.ejbca.core.protocol.ws.CheckRevokationStatus")
    @ResponseWrapper(localName = "checkRevokationStatusResponse", targetNamespace = "http://ws.protocol.core.ejbca.org/", className = "org.ejbca.core.protocol.ws.CheckRevokationStatusResponse")
    @WebResult(name = "return", targetNamespace = "")
    public org.ejbca.core.protocol.ws.RevokeStatus checkRevokationStatus(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    ) throws AuthorizationDeniedException_Exception, EjbcaException_Exception, CADoesntExistsException_Exception;

    @WebMethod
    @RequestWrapper(localName = "generateCryptoTokenKeys", targetNamespace = "http://ws.protocol.core.ejbca.org/", className = "org.ejbca.core.protocol.ws.GenerateCryptoTokenKeys")
    @ResponseWrapper(localName = "generateCryptoTokenKeysResponse", targetNamespace = "http://ws.protocol.core.ejbca.org/", className = "org.ejbca.core.protocol.ws.GenerateCryptoTokenKeysResponse")
    public void generateCryptoTokenKeys(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2
    ) throws AuthorizationDeniedException_Exception, EjbcaException_Exception;

    @WebMethod
    @RequestWrapper(localName = "keyRecoverNewest", targetNamespace = "http://ws.protocol.core.ejbca.org/", className = "org.ejbca.core.protocol.ws.KeyRecoverNewest")
    @ResponseWrapper(localName = "keyRecoverNewestResponse", targetNamespace = "http://ws.protocol.core.ejbca.org/", className = "org.ejbca.core.protocol.ws.KeyRecoverNewestResponse")
    public void keyRecoverNewest(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    ) throws NotFoundException_Exception, CADoesntExistsException_Exception, AuthorizationDeniedException_Exception, ApprovalException_Exception, EjbcaException_Exception, WaitingForApprovalException_Exception;

    @WebMethod
    @RequestWrapper(localName = "editUser", targetNamespace = "http://ws.protocol.core.ejbca.org/", className = "org.ejbca.core.protocol.ws.EditUser")
    @ResponseWrapper(localName = "editUserResponse", targetNamespace = "http://ws.protocol.core.ejbca.org/", className = "org.ejbca.core.protocol.ws.EditUserResponse")
    public void editUser(
        @WebParam(name = "arg0", targetNamespace = "")
        org.ejbca.core.protocol.ws.UserDataVOWS arg0
    ) throws CADoesntExistsException_Exception, AuthorizationDeniedException_Exception, UserDoesntFullfillEndEntityProfile_Exception, ApprovalException_Exception, EjbcaException_Exception, WaitingForApprovalException_Exception;

    @WebMethod
    @RequestWrapper(localName = "spkacRequest", targetNamespace = "http://ws.protocol.core.ejbca.org/", className = "org.ejbca.core.protocol.ws.SpkacRequest")
    @ResponseWrapper(localName = "spkacRequestResponse", targetNamespace = "http://ws.protocol.core.ejbca.org/", className = "org.ejbca.core.protocol.ws.SpkacRequestResponse")
    @WebResult(name = "return", targetNamespace = "")
    public org.ejbca.core.protocol.ws.CertificateResponse spkacRequest(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        java.lang.String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        java.lang.String arg4
    ) throws AuthorizationDeniedException_Exception, NotFoundException_Exception, EjbcaException_Exception, CesecoreException_Exception, CADoesntExistsException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getLastCAChain", targetNamespace = "http://ws.protocol.core.ejbca.org/", className = "org.ejbca.core.protocol.ws.GetLastCAChain")
    @ResponseWrapper(localName = "getLastCAChainResponse", targetNamespace = "http://ws.protocol.core.ejbca.org/", className = "org.ejbca.core.protocol.ws.GetLastCAChainResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<org.ejbca.core.protocol.ws.Certificate> getLastCAChain(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    ) throws AuthorizationDeniedException_Exception, EjbcaException_Exception, CADoesntExistsException_Exception;

    @WebMethod
    @RequestWrapper(localName = "addSubjectToRole", targetNamespace = "http://ws.protocol.core.ejbca.org/", className = "org.ejbca.core.protocol.ws.AddSubjectToRole")
    @ResponseWrapper(localName = "addSubjectToRoleResponse", targetNamespace = "http://ws.protocol.core.ejbca.org/", className = "org.ejbca.core.protocol.ws.AddSubjectToRoleResponse")
    public void addSubjectToRole(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        java.lang.String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        java.lang.String arg4
    ) throws AuthorizationDeniedException_Exception, EjbcaException_Exception;

    @WebMethod
    @RequestWrapper(localName = "deleteUserDataFromSource", targetNamespace = "http://ws.protocol.core.ejbca.org/", className = "org.ejbca.core.protocol.ws.DeleteUserDataFromSource")
    @ResponseWrapper(localName = "deleteUserDataFromSourceResponse", targetNamespace = "http://ws.protocol.core.ejbca.org/", className = "org.ejbca.core.protocol.ws.DeleteUserDataFromSourceResponse")
    @WebResult(name = "return", targetNamespace = "")
    public boolean deleteUserDataFromSource(
        @WebParam(name = "arg0", targetNamespace = "")
        java.util.List<java.lang.String> arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        boolean arg2
    ) throws AuthorizationDeniedException_Exception, MultipleMatchException_Exception, EjbcaException_Exception, UserDataSourceException_Exception;

    @WebMethod
    @RequestWrapper(localName = "findCerts", targetNamespace = "http://ws.protocol.core.ejbca.org/", className = "org.ejbca.core.protocol.ws.FindCerts")
    @ResponseWrapper(localName = "findCertsResponse", targetNamespace = "http://ws.protocol.core.ejbca.org/", className = "org.ejbca.core.protocol.ws.FindCertsResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<org.ejbca.core.protocol.ws.Certificate> findCerts(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        boolean arg1
    ) throws AuthorizationDeniedException_Exception, EjbcaException_Exception;

    @WebMethod
    @RequestWrapper(localName = "certificateRequest", targetNamespace = "http://ws.protocol.core.ejbca.org/", className = "org.ejbca.core.protocol.ws.CertificateRequest")
    @ResponseWrapper(localName = "certificateRequestResponse", targetNamespace = "http://ws.protocol.core.ejbca.org/", className = "org.ejbca.core.protocol.ws.CertificateRequestResponse")
    @WebResult(name = "return", targetNamespace = "")
    public org.ejbca.core.protocol.ws.CertificateResponse certificateRequest(
        @WebParam(name = "arg0", targetNamespace = "")
        org.ejbca.core.protocol.ws.UserDataVOWS arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        int arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        java.lang.String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        java.lang.String arg4
    ) throws NotFoundException_Exception, UserDoesntFullfillEndEntityProfile_Exception, AuthorizationDeniedException_Exception, ApprovalException_Exception, EjbcaException_Exception, WaitingForApprovalException_Exception;

    @WebMethod
    @RequestWrapper(localName = "customLog", targetNamespace = "http://ws.protocol.core.ejbca.org/", className = "org.ejbca.core.protocol.ws.CustomLog")
    @ResponseWrapper(localName = "customLogResponse", targetNamespace = "http://ws.protocol.core.ejbca.org/", className = "org.ejbca.core.protocol.ws.CustomLogResponse")
    public void customLog(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        java.lang.String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        org.ejbca.core.protocol.ws.Certificate arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        java.lang.String arg5
    ) throws AuthorizationDeniedException_Exception, EjbcaException_Exception, CADoesntExistsException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getEjbcaVersion", targetNamespace = "http://ws.protocol.core.ejbca.org/", className = "org.ejbca.core.protocol.ws.GetEjbcaVersion")
    @ResponseWrapper(localName = "getEjbcaVersionResponse", targetNamespace = "http://ws.protocol.core.ejbca.org/", className = "org.ejbca.core.protocol.ws.GetEjbcaVersionResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String getEjbcaVersion();

    @WebMethod
    @RequestWrapper(localName = "getAuthorizedEndEntityProfiles", targetNamespace = "http://ws.protocol.core.ejbca.org/", className = "org.ejbca.core.protocol.ws.GetAuthorizedEndEntityProfiles")
    @ResponseWrapper(localName = "getAuthorizedEndEntityProfilesResponse", targetNamespace = "http://ws.protocol.core.ejbca.org/", className = "org.ejbca.core.protocol.ws.GetAuthorizedEndEntityProfilesResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<org.ejbca.core.protocol.ws.NameAndId> getAuthorizedEndEntityProfiles() throws AuthorizationDeniedException_Exception, EjbcaException_Exception;

    @WebMethod
    @RequestWrapper(localName = "existsHardToken", targetNamespace = "http://ws.protocol.core.ejbca.org/", className = "org.ejbca.core.protocol.ws.ExistsHardToken")
    @ResponseWrapper(localName = "existsHardTokenResponse", targetNamespace = "http://ws.protocol.core.ejbca.org/", className = "org.ejbca.core.protocol.ws.ExistsHardTokenResponse")
    @WebResult(name = "return", targetNamespace = "")
    public boolean existsHardToken(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    ) throws EjbcaException_Exception;

    @WebMethod
    @RequestWrapper(localName = "cvcRequest", targetNamespace = "http://ws.protocol.core.ejbca.org/", className = "org.ejbca.core.protocol.ws.CvcRequest")
    @ResponseWrapper(localName = "cvcRequestResponse", targetNamespace = "http://ws.protocol.core.ejbca.org/", className = "org.ejbca.core.protocol.ws.CvcRequestResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<org.ejbca.core.protocol.ws.Certificate> cvcRequest(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2
    ) throws NotFoundException_Exception, SignRequestException_Exception, CADoesntExistsException_Exception, UserDoesntFullfillEndEntityProfile_Exception, AuthorizationDeniedException_Exception, ApprovalException_Exception, EjbcaException_Exception, CesecoreException_Exception, CertificateExpiredException_Exception, WaitingForApprovalException_Exception;

    @WebMethod
    @RequestWrapper(localName = "isAuthorized", targetNamespace = "http://ws.protocol.core.ejbca.org/", className = "org.ejbca.core.protocol.ws.IsAuthorized")
    @ResponseWrapper(localName = "isAuthorizedResponse", targetNamespace = "http://ws.protocol.core.ejbca.org/", className = "org.ejbca.core.protocol.ws.IsAuthorizedResponse")
    @WebResult(name = "return", targetNamespace = "")
    public boolean isAuthorized(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    ) throws EjbcaException_Exception;

    @WebMethod
    @RequestWrapper(localName = "republishCertificate", targetNamespace = "http://ws.protocol.core.ejbca.org/", className = "org.ejbca.core.protocol.ws.RepublishCertificate")
    @ResponseWrapper(localName = "republishCertificateResponse", targetNamespace = "http://ws.protocol.core.ejbca.org/", className = "org.ejbca.core.protocol.ws.RepublishCertificateResponse")
    public void republishCertificate(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    ) throws AuthorizationDeniedException_Exception, PublisherException_Exception, EjbcaException_Exception, CADoesntExistsException_Exception;

    @WebMethod
    @RequestWrapper(localName = "caCertResponse", targetNamespace = "http://ws.protocol.core.ejbca.org/", className = "org.ejbca.core.protocol.ws.CaCertResponse")
    @ResponseWrapper(localName = "caCertResponseResponse", targetNamespace = "http://ws.protocol.core.ejbca.org/", className = "org.ejbca.core.protocol.ws.CaCertResponseResponse")
    public void caCertResponse(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        byte[] arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.util.List<byte[]> arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        java.lang.String arg3
    ) throws AuthorizationDeniedException_Exception, ApprovalException_Exception, EjbcaException_Exception, CesecoreException_Exception, WaitingForApprovalException_Exception;

    @WebMethod
    @RequestWrapper(localName = "createCRL", targetNamespace = "http://ws.protocol.core.ejbca.org/", className = "org.ejbca.core.protocol.ws.CreateCRL")
    @ResponseWrapper(localName = "createCRLResponse", targetNamespace = "http://ws.protocol.core.ejbca.org/", className = "org.ejbca.core.protocol.ws.CreateCRLResponse")
    public void createCRL(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    ) throws CAOfflineException_Exception, ApprovalRequestExpiredException_Exception, CADoesntExistsException_Exception, ApprovalException_Exception, CryptoTokenOfflineException_Exception, EjbcaException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getAvailableCAsInProfile", targetNamespace = "http://ws.protocol.core.ejbca.org/", className = "org.ejbca.core.protocol.ws.GetAvailableCAsInProfile")
    @ResponseWrapper(localName = "getAvailableCAsInProfileResponse", targetNamespace = "http://ws.protocol.core.ejbca.org/", className = "org.ejbca.core.protocol.ws.GetAvailableCAsInProfileResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<org.ejbca.core.protocol.ws.NameAndId> getAvailableCAsInProfile(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0
    ) throws AuthorizationDeniedException_Exception, EjbcaException_Exception;

    @WebMethod
    @RequestWrapper(localName = "pkcs12Req", targetNamespace = "http://ws.protocol.core.ejbca.org/", className = "org.ejbca.core.protocol.ws.Pkcs12Req")
    @ResponseWrapper(localName = "pkcs12ReqResponse", targetNamespace = "http://ws.protocol.core.ejbca.org/", className = "org.ejbca.core.protocol.ws.Pkcs12ReqResponse")
    @WebResult(name = "return", targetNamespace = "")
    public org.ejbca.core.protocol.ws.KeyStore pkcs12Req(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        java.lang.String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        java.lang.String arg4
    ) throws AuthorizationDeniedException_Exception, NotFoundException_Exception, EjbcaException_Exception, CADoesntExistsException_Exception;

    @WebMethod
    @RequestWrapper(localName = "keyRecover", targetNamespace = "http://ws.protocol.core.ejbca.org/", className = "org.ejbca.core.protocol.ws.KeyRecover")
    @ResponseWrapper(localName = "keyRecoverResponse", targetNamespace = "http://ws.protocol.core.ejbca.org/", className = "org.ejbca.core.protocol.ws.KeyRecoverResponse")
    public void keyRecover(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2
    ) throws NotFoundException_Exception, CADoesntExistsException_Exception, AuthorizationDeniedException_Exception, ApprovalException_Exception, EjbcaException_Exception, WaitingForApprovalException_Exception;

    @WebMethod
    @RequestWrapper(localName = "caRenewCertRequest", targetNamespace = "http://ws.protocol.core.ejbca.org/", className = "org.ejbca.core.protocol.ws.CaRenewCertRequest")
    @ResponseWrapper(localName = "caRenewCertRequestResponse", targetNamespace = "http://ws.protocol.core.ejbca.org/", className = "org.ejbca.core.protocol.ws.CaRenewCertRequestResponse")
    @WebResult(name = "return", targetNamespace = "")
    public byte[] caRenewCertRequest(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.util.List<byte[]> arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        boolean arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        boolean arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        boolean arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        java.lang.String arg5
    ) throws AuthorizationDeniedException_Exception, ApprovalException_Exception, EjbcaException_Exception, CADoesntExistsException_Exception, WaitingForApprovalException_Exception;

    @WebMethod
    @RequestWrapper(localName = "fetchUserData", targetNamespace = "http://ws.protocol.core.ejbca.org/", className = "org.ejbca.core.protocol.ws.FetchUserData")
    @ResponseWrapper(localName = "fetchUserDataResponse", targetNamespace = "http://ws.protocol.core.ejbca.org/", className = "org.ejbca.core.protocol.ws.FetchUserDataResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<org.ejbca.core.protocol.ws.UserDataSourceVOWS> fetchUserData(
        @WebParam(name = "arg0", targetNamespace = "")
        java.util.List<java.lang.String> arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    ) throws AuthorizationDeniedException_Exception, EjbcaException_Exception, UserDataSourceException_Exception;

    @WebMethod
    @RequestWrapper(localName = "pkcs10Request", targetNamespace = "http://ws.protocol.core.ejbca.org/", className = "org.ejbca.core.protocol.ws.Pkcs10Request")
    @ResponseWrapper(localName = "pkcs10RequestResponse", targetNamespace = "http://ws.protocol.core.ejbca.org/", className = "org.ejbca.core.protocol.ws.Pkcs10RequestResponse")
    @WebResult(name = "return", targetNamespace = "")
    public org.ejbca.core.protocol.ws.CertificateResponse pkcs10Request(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        java.lang.String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        java.lang.String arg4
    ) throws AuthorizationDeniedException_Exception, NotFoundException_Exception, EjbcaException_Exception, CesecoreException_Exception, CADoesntExistsException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getHardTokenDatas", targetNamespace = "http://ws.protocol.core.ejbca.org/", className = "org.ejbca.core.protocol.ws.GetHardTokenDatas")
    @ResponseWrapper(localName = "getHardTokenDatasResponse", targetNamespace = "http://ws.protocol.core.ejbca.org/", className = "org.ejbca.core.protocol.ws.GetHardTokenDatasResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<org.ejbca.core.protocol.ws.HardTokenDataWS> getHardTokenDatas(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        boolean arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        boolean arg2
    ) throws AuthorizationDeniedException_Exception, EjbcaException_Exception, CADoesntExistsException_Exception;

    @WebMethod
    @RequestWrapper(localName = "revokeToken", targetNamespace = "http://ws.protocol.core.ejbca.org/", className = "org.ejbca.core.protocol.ws.RevokeToken")
    @ResponseWrapper(localName = "revokeTokenResponse", targetNamespace = "http://ws.protocol.core.ejbca.org/", className = "org.ejbca.core.protocol.ws.RevokeTokenResponse")
    public void revokeToken(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1
    ) throws NotFoundException_Exception, AlreadyRevokedException_Exception, CADoesntExistsException_Exception, AuthorizationDeniedException_Exception, ApprovalException_Exception, EjbcaException_Exception, WaitingForApprovalException_Exception;

    @WebMethod
    @RequestWrapper(localName = "softTokenRequest", targetNamespace = "http://ws.protocol.core.ejbca.org/", className = "org.ejbca.core.protocol.ws.SoftTokenRequest")
    @ResponseWrapper(localName = "softTokenRequestResponse", targetNamespace = "http://ws.protocol.core.ejbca.org/", className = "org.ejbca.core.protocol.ws.SoftTokenRequestResponse")
    @WebResult(name = "return", targetNamespace = "")
    public org.ejbca.core.protocol.ws.KeyStore softTokenRequest(
        @WebParam(name = "arg0", targetNamespace = "")
        org.ejbca.core.protocol.ws.UserDataVOWS arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        java.lang.String arg3
    ) throws NotFoundException_Exception, CADoesntExistsException_Exception, UserDoesntFullfillEndEntityProfile_Exception, AuthorizationDeniedException_Exception, ApprovalException_Exception, EjbcaException_Exception, WaitingForApprovalException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getLatestCRL", targetNamespace = "http://ws.protocol.core.ejbca.org/", className = "org.ejbca.core.protocol.ws.GetLatestCRL")
    @ResponseWrapper(localName = "getLatestCRLResponse", targetNamespace = "http://ws.protocol.core.ejbca.org/", className = "org.ejbca.core.protocol.ws.GetLatestCRLResponse")
    @WebResult(name = "return", targetNamespace = "")
    public byte[] getLatestCRL(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        boolean arg1
    ) throws EjbcaException_Exception, CADoesntExistsException_Exception;

    @WebMethod
    @RequestWrapper(localName = "removeSubjectFromRole", targetNamespace = "http://ws.protocol.core.ejbca.org/", className = "org.ejbca.core.protocol.ws.RemoveSubjectFromRole")
    @ResponseWrapper(localName = "removeSubjectFromRoleResponse", targetNamespace = "http://ws.protocol.core.ejbca.org/", className = "org.ejbca.core.protocol.ws.RemoveSubjectFromRoleResponse")
    public void removeSubjectFromRole(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        java.lang.String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        java.lang.String arg4
    ) throws AuthorizationDeniedException_Exception, EjbcaException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getAvailableCAs", targetNamespace = "http://ws.protocol.core.ejbca.org/", className = "org.ejbca.core.protocol.ws.GetAvailableCAs")
    @ResponseWrapper(localName = "getAvailableCAsResponse", targetNamespace = "http://ws.protocol.core.ejbca.org/", className = "org.ejbca.core.protocol.ws.GetAvailableCAsResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<org.ejbca.core.protocol.ws.NameAndId> getAvailableCAs() throws AuthorizationDeniedException_Exception, EjbcaException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getCertificatesByExpirationTimeAndIssuer", targetNamespace = "http://ws.protocol.core.ejbca.org/", className = "org.ejbca.core.protocol.ws.GetCertificatesByExpirationTimeAndIssuer")
    @ResponseWrapper(localName = "getCertificatesByExpirationTimeAndIssuerResponse", targetNamespace = "http://ws.protocol.core.ejbca.org/", className = "org.ejbca.core.protocol.ws.GetCertificatesByExpirationTimeAndIssuerResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<org.ejbca.core.protocol.ws.Certificate> getCertificatesByExpirationTimeAndIssuer(
        @WebParam(name = "arg0", targetNamespace = "")
        long arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        int arg2
    ) throws EjbcaException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getLastCertChain", targetNamespace = "http://ws.protocol.core.ejbca.org/", className = "org.ejbca.core.protocol.ws.GetLastCertChain")
    @ResponseWrapper(localName = "getLastCertChainResponse", targetNamespace = "http://ws.protocol.core.ejbca.org/", className = "org.ejbca.core.protocol.ws.GetLastCertChainResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<org.ejbca.core.protocol.ws.Certificate> getLastCertChain(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    ) throws AuthorizationDeniedException_Exception, EjbcaException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getCertificatesByExpirationTime", targetNamespace = "http://ws.protocol.core.ejbca.org/", className = "org.ejbca.core.protocol.ws.GetCertificatesByExpirationTime")
    @ResponseWrapper(localName = "getCertificatesByExpirationTimeResponse", targetNamespace = "http://ws.protocol.core.ejbca.org/", className = "org.ejbca.core.protocol.ws.GetCertificatesByExpirationTimeResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<org.ejbca.core.protocol.ws.Certificate> getCertificatesByExpirationTime(
        @WebParam(name = "arg0", targetNamespace = "")
        long arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1
    ) throws EjbcaException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getAvailableCertificateProfiles", targetNamespace = "http://ws.protocol.core.ejbca.org/", className = "org.ejbca.core.protocol.ws.GetAvailableCertificateProfiles")
    @ResponseWrapper(localName = "getAvailableCertificateProfilesResponse", targetNamespace = "http://ws.protocol.core.ejbca.org/", className = "org.ejbca.core.protocol.ws.GetAvailableCertificateProfilesResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<org.ejbca.core.protocol.ws.NameAndId> getAvailableCertificateProfiles(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0
    ) throws AuthorizationDeniedException_Exception, EjbcaException_Exception;

    @WebMethod
    @RequestWrapper(localName = "createCA", targetNamespace = "http://ws.protocol.core.ejbca.org/", className = "org.ejbca.core.protocol.ws.CreateCA")
    @ResponseWrapper(localName = "createCAResponse", targetNamespace = "http://ws.protocol.core.ejbca.org/", className = "org.ejbca.core.protocol.ws.CreateCAResponse")
    public void createCA(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        long arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        java.lang.String arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        java.lang.String arg5,
        @WebParam(name = "arg6", targetNamespace = "")
        int arg6,
        @WebParam(name = "arg7", targetNamespace = "")
        java.lang.String arg7,
        @WebParam(name = "arg8", targetNamespace = "")
        java.util.List<org.ejbca.core.protocol.ws.KeyValuePair> arg8,
        @WebParam(name = "arg9", targetNamespace = "")
        java.util.List<org.ejbca.core.protocol.ws.KeyValuePair> arg9
    ) throws AuthorizationDeniedException_Exception, EjbcaException_Exception;

    @WebMethod
    @RequestWrapper(localName = "isApproved", targetNamespace = "http://ws.protocol.core.ejbca.org/", className = "org.ejbca.core.protocol.ws.IsApproved")
    @ResponseWrapper(localName = "isApprovedResponse", targetNamespace = "http://ws.protocol.core.ejbca.org/", className = "org.ejbca.core.protocol.ws.IsApprovedResponse")
    @WebResult(name = "return", targetNamespace = "")
    public int isApproved(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0
    ) throws ApprovalException_Exception, EjbcaException_Exception, ApprovalRequestExpiredException_Exception;

    @WebMethod
    @RequestWrapper(localName = "revokeUser", targetNamespace = "http://ws.protocol.core.ejbca.org/", className = "org.ejbca.core.protocol.ws.RevokeUser")
    @ResponseWrapper(localName = "revokeUserResponse", targetNamespace = "http://ws.protocol.core.ejbca.org/", className = "org.ejbca.core.protocol.ws.RevokeUserResponse")
    public void revokeUser(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        boolean arg2
    ) throws NotFoundException_Exception, AlreadyRevokedException_Exception, CADoesntExistsException_Exception, AuthorizationDeniedException_Exception, ApprovalException_Exception, EjbcaException_Exception, WaitingForApprovalException_Exception;

    @WebMethod
    @RequestWrapper(localName = "revokeCert", targetNamespace = "http://ws.protocol.core.ejbca.org/", className = "org.ejbca.core.protocol.ws.RevokeCert")
    @ResponseWrapper(localName = "revokeCertResponse", targetNamespace = "http://ws.protocol.core.ejbca.org/", className = "org.ejbca.core.protocol.ws.RevokeCertResponse")
    public void revokeCert(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        int arg2
    ) throws NotFoundException_Exception, AlreadyRevokedException_Exception, CADoesntExistsException_Exception, AuthorizationDeniedException_Exception, ApprovalException_Exception, EjbcaException_Exception, WaitingForApprovalException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getCertificate", targetNamespace = "http://ws.protocol.core.ejbca.org/", className = "org.ejbca.core.protocol.ws.GetCertificate")
    @ResponseWrapper(localName = "getCertificateResponse", targetNamespace = "http://ws.protocol.core.ejbca.org/", className = "org.ejbca.core.protocol.ws.GetCertificateResponse")
    @WebResult(name = "return", targetNamespace = "")
    public org.ejbca.core.protocol.ws.Certificate getCertificate(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    ) throws AuthorizationDeniedException_Exception, EjbcaException_Exception, CADoesntExistsException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getPublisherQueueLength", targetNamespace = "http://ws.protocol.core.ejbca.org/", className = "org.ejbca.core.protocol.ws.GetPublisherQueueLength")
    @ResponseWrapper(localName = "getPublisherQueueLengthResponse", targetNamespace = "http://ws.protocol.core.ejbca.org/", className = "org.ejbca.core.protocol.ws.GetPublisherQueueLengthResponse")
    @WebResult(name = "return", targetNamespace = "")
    public int getPublisherQueueLength(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    ) throws EjbcaException_Exception;
}
