
package org.ejbca.core.protocol.ws;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.3
 * 2018-08-06T10:49:50.915+02:00
 * Generated source version: 3.1.3
 */

@WebFault(name = "EndEntityProfileNotFoundException", targetNamespace = "http://ws.protocol.core.ejbca.org/")
public class EndEntityProfileNotFoundException_Exception extends Exception {
    
    private org.ejbca.core.protocol.ws.EndEntityProfileNotFoundException endEntityProfileNotFoundException;

    public EndEntityProfileNotFoundException_Exception() {
        super();
    }
    
    public EndEntityProfileNotFoundException_Exception(String message) {
        super(message);
    }
    
    public EndEntityProfileNotFoundException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public EndEntityProfileNotFoundException_Exception(String message, org.ejbca.core.protocol.ws.EndEntityProfileNotFoundException endEntityProfileNotFoundException) {
        super(message);
        this.endEntityProfileNotFoundException = endEntityProfileNotFoundException;
    }

    public EndEntityProfileNotFoundException_Exception(String message, org.ejbca.core.protocol.ws.EndEntityProfileNotFoundException endEntityProfileNotFoundException, Throwable cause) {
        super(message, cause);
        this.endEntityProfileNotFoundException = endEntityProfileNotFoundException;
    }

    public org.ejbca.core.protocol.ws.EndEntityProfileNotFoundException getFaultInfo() {
        return this.endEntityProfileNotFoundException;
    }
}
