
package org.ejbca.core.protocol.ws;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.3
 * 2018-09-27T08:23:56.005+02:00
 * Generated source version: 3.1.3
 */

@WebFault(name = "IllegalQueryException", targetNamespace = "http://ws.protocol.core.ejbca.org/")
public class IllegalQueryException_Exception extends Exception {
    
    private org.ejbca.core.protocol.ws.IllegalQueryException illegalQueryException;

    public IllegalQueryException_Exception() {
        super();
    }
    
    public IllegalQueryException_Exception(String message) {
        super(message);
    }
    
    public IllegalQueryException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public IllegalQueryException_Exception(String message, org.ejbca.core.protocol.ws.IllegalQueryException illegalQueryException) {
        super(message);
        this.illegalQueryException = illegalQueryException;
    }

    public IllegalQueryException_Exception(String message, org.ejbca.core.protocol.ws.IllegalQueryException illegalQueryException, Throwable cause) {
        super(message, cause);
        this.illegalQueryException = illegalQueryException;
    }

    public org.ejbca.core.protocol.ws.IllegalQueryException getFaultInfo() {
        return this.illegalQueryException;
    }
}
