
package org.ejbca.core.protocol.ws;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.3
 * 2018-09-27T08:23:56.024+02:00
 * Generated source version: 3.1.3
 */

@WebFault(name = "MultipleMatchException", targetNamespace = "http://ws.protocol.core.ejbca.org/")
public class MultipleMatchException_Exception extends Exception {
    
    private org.ejbca.core.protocol.ws.MultipleMatchException multipleMatchException;

    public MultipleMatchException_Exception() {
        super();
    }
    
    public MultipleMatchException_Exception(String message) {
        super(message);
    }
    
    public MultipleMatchException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public MultipleMatchException_Exception(String message, org.ejbca.core.protocol.ws.MultipleMatchException multipleMatchException) {
        super(message);
        this.multipleMatchException = multipleMatchException;
    }

    public MultipleMatchException_Exception(String message, org.ejbca.core.protocol.ws.MultipleMatchException multipleMatchException, Throwable cause) {
        super(message, cause);
        this.multipleMatchException = multipleMatchException;
    }

    public org.ejbca.core.protocol.ws.MultipleMatchException getFaultInfo() {
        return this.multipleMatchException;
    }
}
