
package org.ejbca.core.protocol.ws;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.3
 * 2018-09-27T08:23:55.954+02:00
 * Generated source version: 3.1.3
 */

@WebFault(name = "NotFoundException", targetNamespace = "http://ws.protocol.core.ejbca.org/")
public class NotFoundException_Exception extends Exception {
    
    private org.ejbca.core.protocol.ws.NotFoundException notFoundException;

    public NotFoundException_Exception() {
        super();
    }
    
    public NotFoundException_Exception(String message) {
        super(message);
    }
    
    public NotFoundException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public NotFoundException_Exception(String message, org.ejbca.core.protocol.ws.NotFoundException notFoundException) {
        super(message);
        this.notFoundException = notFoundException;
    }

    public NotFoundException_Exception(String message, org.ejbca.core.protocol.ws.NotFoundException notFoundException, Throwable cause) {
        super(message, cause);
        this.notFoundException = notFoundException;
    }

    public org.ejbca.core.protocol.ws.NotFoundException getFaultInfo() {
        return this.notFoundException;
    }
}
