
package org.ejbca.core.protocol.ws;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.3
 * 2018-08-06T10:49:50.930+02:00
 * Generated source version: 3.1.3
 */

@WebFault(name = "RevokeBackDateNotAllowedForProfileException", targetNamespace = "http://ws.protocol.core.ejbca.org/")
public class RevokeBackDateNotAllowedForProfileException_Exception extends Exception {
    
    private org.ejbca.core.protocol.ws.RevokeBackDateNotAllowedForProfileException revokeBackDateNotAllowedForProfileException;

    public RevokeBackDateNotAllowedForProfileException_Exception() {
        super();
    }
    
    public RevokeBackDateNotAllowedForProfileException_Exception(String message) {
        super(message);
    }
    
    public RevokeBackDateNotAllowedForProfileException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public RevokeBackDateNotAllowedForProfileException_Exception(String message, org.ejbca.core.protocol.ws.RevokeBackDateNotAllowedForProfileException revokeBackDateNotAllowedForProfileException) {
        super(message);
        this.revokeBackDateNotAllowedForProfileException = revokeBackDateNotAllowedForProfileException;
    }

    public RevokeBackDateNotAllowedForProfileException_Exception(String message, org.ejbca.core.protocol.ws.RevokeBackDateNotAllowedForProfileException revokeBackDateNotAllowedForProfileException, Throwable cause) {
        super(message, cause);
        this.revokeBackDateNotAllowedForProfileException = revokeBackDateNotAllowedForProfileException;
    }

    public org.ejbca.core.protocol.ws.RevokeBackDateNotAllowedForProfileException getFaultInfo() {
        return this.revokeBackDateNotAllowedForProfileException;
    }
}
