
package org.ejbca.core.protocol.ws;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.3
 * 2018-08-06T10:49:50.911+02:00
 * Generated source version: 3.1.3
 */

@WebFault(name = "UnknownProfileTypeException", targetNamespace = "http://ws.protocol.core.ejbca.org/")
public class UnknownProfileTypeException_Exception extends Exception {
    
    private org.ejbca.core.protocol.ws.UnknownProfileTypeException unknownProfileTypeException;

    public UnknownProfileTypeException_Exception() {
        super();
    }
    
    public UnknownProfileTypeException_Exception(String message) {
        super(message);
    }
    
    public UnknownProfileTypeException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public UnknownProfileTypeException_Exception(String message, org.ejbca.core.protocol.ws.UnknownProfileTypeException unknownProfileTypeException) {
        super(message);
        this.unknownProfileTypeException = unknownProfileTypeException;
    }

    public UnknownProfileTypeException_Exception(String message, org.ejbca.core.protocol.ws.UnknownProfileTypeException unknownProfileTypeException, Throwable cause) {
        super(message, cause);
        this.unknownProfileTypeException = unknownProfileTypeException;
    }

    public org.ejbca.core.protocol.ws.UnknownProfileTypeException getFaultInfo() {
        return this.unknownProfileTypeException;
    }
}
