
package org.ejbca.core.protocol.ws;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.3
 * 2018-09-27T08:23:56.010+02:00
 * Generated source version: 3.1.3
 */

@WebFault(name = "UserDoesntFullfillEndEntityProfile", targetNamespace = "http://ws.protocol.core.ejbca.org/")
public class UserDoesntFullfillEndEntityProfile_Exception extends Exception {
    
    private org.ejbca.core.protocol.ws.UserDoesntFullfillEndEntityProfile userDoesntFullfillEndEntityProfile;

    public UserDoesntFullfillEndEntityProfile_Exception() {
        super();
    }
    
    public UserDoesntFullfillEndEntityProfile_Exception(String message) {
        super(message);
    }
    
    public UserDoesntFullfillEndEntityProfile_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public UserDoesntFullfillEndEntityProfile_Exception(String message, org.ejbca.core.protocol.ws.UserDoesntFullfillEndEntityProfile userDoesntFullfillEndEntityProfile) {
        super(message);
        this.userDoesntFullfillEndEntityProfile = userDoesntFullfillEndEntityProfile;
    }

    public UserDoesntFullfillEndEntityProfile_Exception(String message, org.ejbca.core.protocol.ws.UserDoesntFullfillEndEntityProfile userDoesntFullfillEndEntityProfile, Throwable cause) {
        super(message, cause);
        this.userDoesntFullfillEndEntityProfile = userDoesntFullfillEndEntityProfile;
    }

    public org.ejbca.core.protocol.ws.UserDoesntFullfillEndEntityProfile getFaultInfo() {
        return this.userDoesntFullfillEndEntityProfile;
    }
}
